import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import img from "../../assets/Group.png";
import { Star } from "lucide-react";
export default function Testimonials() {
    return (_jsxs("section", { className: "mt-20 px-6 md:px-12", children: [_jsx("h2", { className: "text-white", style: { fontSize: "36px", fontWeight: 500 }, children: "Testimonials" }), _jsxs("div", { className: "grid grid-cols-3 gap-4 mt-6", children: [_jsxs("div", { className: "p-4 col-span-2 flex justify-between", children: [_jsxs("div", { className: "bg-white/10 backdrop-blur-lg border border-white/20 \r\n                 p-6 w-full max-w-2xl \r\n                  shadow-xl transform transition-transform duration-500 \r\n                  hover:rotate-y-6 hover:scale-105 scale-90", style: { perspective: "1000px", width: 300, borderBottomLeftRadius: 50 }, children: [_jsx("img", { src: img, alt: "user", className: " shadow-md" }), _jsx("div", { className: "flex items-center gap-6", children: _jsxs("div", { children: [_jsx("p", { className: "text-white italic text-lg mb-2", style: { fontSize: 15, marginTop: 5 }, children: "\u201CThis platform transformed my health journey \u2014 I feel stronger and more confident every day.\u201D" }), _jsxs("div", { style: { width: "100%", display: "flex", flexDirection: "row", justifyContent: "flex-end", position: "relative" }, children: [_jsxs("div", { children: [_jsx("div", { className: "flex space-x-1 text-yellow-400", style: { justifyContent: "flex-end", marginRight: 55 }, children: Array.from({ length: 5 }).map((_, i) => (_jsx(Star, { className: "w-3 h-3 fill-yellow-400" }, i))) }), _jsx("div", { style: { width: 200, height: 30, background: "#000", marginTop: 10, borderTopLeftRadius: 20, borderBottomLeftRadius: 20, display: "flex", justifyContent: "flex-end", alignItems: "center", marginRight: 10 }, children: _jsx("p", { style: { color: "#fff", fontSize: 12, marginRight: 55, fontFamily: "'Roboto', sans-serif" }, children: "Pavan Ahirwar" }) })] }), _jsx("div", { style: { width: 55, height: 55, background: "red", borderRadius: 100, position: "absolute", right: 0, top: 0 }, children: _jsx("img", { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "profile", style: {
                                                                    width: "100%",
                                                                    height: "100%",
                                                                    objectFit: "cover",
                                                                    borderRadius: 100
                                                                } }) })] })] }) })] }), _jsxs("div", { className: "bg-white/10 backdrop-blur-lg border border-white/20 \r\n                 p-6 w-full max-w-2xl \r\n                  shadow-xl transform transition-transform duration-500 \r\n                  hover:rotate-y-6 hover:scale-105 scale-100", style: { perspective: "1000px", width: 300, borderBottomLeftRadius: 50 }, children: [_jsx("img", { src: img, alt: "user", className: " shadow-md" }), _jsx("div", { className: "flex items-center gap-6", children: _jsxs("div", { children: [_jsx("p", { className: "text-white italic text-lg mb-2", style: { fontSize: 15, marginTop: 5 }, children: "\u201CThis platform transformed my health journey \u2014 I feel stronger and more confident every day.\u201D" }), _jsxs("div", { style: { width: "100%", display: "flex", flexDirection: "row", justifyContent: "flex-end", position: "relative" }, children: [_jsxs("div", { children: [_jsx("div", { className: "flex space-x-1 text-yellow-400", style: { justifyContent: "flex-end", marginRight: 55 }, children: Array.from({ length: 5 }).map((_, i) => (_jsx(Star, { className: "w-3 h-3 fill-yellow-400" }, i))) }), _jsx("div", { style: { width: 200, height: 30, background: "#000", marginTop: 10, borderTopLeftRadius: 20, borderBottomLeftRadius: 20, display: "flex", justifyContent: "flex-end", alignItems: "center", marginRight: 10 }, children: _jsx("p", { style: { color: "#fff", fontSize: 12, marginRight: 55, fontFamily: "'Roboto', sans-serif" }, children: "Pavan Ahirwar" }) })] }), _jsx("div", { style: { width: 55, height: 55, background: "red", borderRadius: 100, position: "absolute", right: 0, top: 0 }, children: _jsx("img", { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "profile", style: {
                                                                    width: "100%",
                                                                    height: "100%",
                                                                    objectFit: "cover",
                                                                    borderRadius: 100
                                                                } }) })] })] }) })] }), _jsxs("div", { className: "bg-white/10 backdrop-blur-lg border border-white/20 \r\n                 p-6 w-full max-w-2xl \r\n                  shadow-xl transform transition-transform duration-500 \r\n                  hover:rotate-y-6 hover:scale-105 scale-110", style: { perspective: "1000px", width: 300, borderBottomLeftRadius: 50 }, children: [_jsx("img", { src: img, alt: "user", className: " shadow-md" }), _jsx("div", { className: "flex items-center gap-6", children: _jsxs("div", { children: [_jsx("p", { className: "text-white italic text-lg mb-2", style: { fontSize: 15, marginTop: 5 }, children: "\u201CThis platform transformed my health journey \u2014 I feel stronger and more confident every day.\u201D" }), _jsxs("div", { style: { width: "100%", display: "flex", flexDirection: "row", justifyContent: "flex-end", position: "relative" }, children: [_jsxs("div", { children: [_jsx("div", { className: "flex space-x-1 text-yellow-400", style: { justifyContent: "flex-end", marginRight: 55 }, children: Array.from({ length: 5 }).map((_, i) => (_jsx(Star, { className: "w-3 h-3 fill-yellow-400" }, i))) }), _jsx("div", { style: { width: 200, height: 30, background: "#000", marginTop: 10, borderTopLeftRadius: 20, borderBottomLeftRadius: 20, display: "flex", justifyContent: "flex-end", alignItems: "center", marginRight: 10 }, children: _jsx("p", { style: { color: "#fff", fontSize: 12, marginRight: 55, fontFamily: "'Roboto', sans-serif" }, children: "Pavan Ahirwar" }) })] }), _jsx("div", { style: { width: 55, height: 55, background: "red", borderRadius: 100, position: "absolute", right: 0, top: 0 }, children: _jsx("img", { src: "https://randomuser.me/api/portraits/men/32.jpg", alt: "profile", style: {
                                                                    width: "100%",
                                                                    height: "100%",
                                                                    objectFit: "cover",
                                                                    borderRadius: 100
                                                                } }) })] })] }) })] })] }), _jsx("div", { className: " text-white p-4 col-span-1 flex items-center justify-center flex-col rounded", children: _jsxs("div", { style: { backgroundColor: "#010D3D", width: "100%", height: 200, borderTopLeftRadius: 100, borderBottomLeftRadius: 100, padding: 20, boxSizing: "border-box" }, children: [_jsx("h1", { className: "text-3xl font-bold mt-5 ml-5 ", style: { fontFamily: "'Roboto', sans-serif", }, children: "Results That Speak" }), _jsx("p", { className: "mt-5 ml-5", style: { fontFamily: "'Roboto', sans-serif", }, children: "Hear from our happy clients and discover how our services have transformed their health, recovery, and overall wellbeing." })] }) })] })] }));
}
